.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Clay Freeman <git@clayfreeman.com>.
.\"
.TH CREATE-SITE 8 "December 12 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
create-site \- Creates a shared hosting site.
.SH SYNOPSIS
.B create-site
.RI [ options ] " account template domain"
.RI [ domain ] " ..."
.SH DESCRIPTION
.B create-site
will attempt to create the necessary nginx and OpenDKIM configuration files for
the requested \fIdomain\fP(s) using the specified \fItemplate\fP.
.PP
First, \fBcreate-site\fP will ensure that the provided \fIaccount\fP already
exists within the internal database. Next, a 1024-bit RSA private key is
generated for each provided \fIdomain\fP using PHP's OpenSSL extension.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Display the help message.
.TP
.B \-q, \-\-quiet
Do not output any message.
.TP
.B \-V, \-\-version
Display the application version.
.TP
.B \-\-ansi
Force ANSI output.
.TP
.B \-\-no\-ansi
Disable ANSI output.
.TP
.B \-n, \-\-no\-interaction
Do not ask any interactive question.
.TP
.B \-v|vv|vvv, \-\-verbose
Increase the verbosity of messages: 1 for normal output, 2 for more verbose
output and 3 for debug.
.SH SEE ALSO
.BR delete-site (8).
