.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Clay Freeman <git@clayfreeman.com>.
.\"
.TH REWRITE-ENVELOPE 8 "December 12 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rewrite-envelope \- Milter for rewriting envelope domains of e-mail.
.SH SYNOPSIS
.B rewrite-envelope
.RI [ options ]
.SH DESCRIPTION
.B rewrite-envelope
is a milter that replaces the domain in the envelope sender address with the
domain in the \fLFrom\fP header. This is so that strict DMARC rules can be
enforced.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Display the help message.
.TP
.B \-d, \-\-debug
Run in the foreground with verbose logging.
.TP
.B \-g, \-\-group
Run the milter as this group.
.TP
.B \-p, \-\-pid
Write a PID file to this path.
.TP
.B \-s, \-\-socket
IPv4, IPv6 or Unix socket to listen on.
.TP
.B \-u, \-\-user
Run the milter as this user.
