.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Clay Freeman <git@clayfreeman.com>.
.\"
.TH WEB-PERMISSIONS 8 "December 12 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
web-permissions \- Force administrative permissions on shared hosting accounts.
.SH SYNOPSIS
.B web-permissions
[ \fIgroup\fP \fIusername\fP ]
.SH DESCRIPTION
.B web-permissions
will recursively force the provided \fIgroup\fP ownership on \fIusername\fP's
\fLpublic_html\fP directory and also set file mode 2775 for all directories and
0664 for all files within the same directory.
.PP
\fIgroup\fP is a Unix group and \fIusername\fP is a Unix user. Each argument is
compatible with names found via
.BR nsswitch.conf (5).
