#!/usr/bin/env php
<?php
  /**
   * This file serves as a config file updater for shared-hosting.
   *
   * @copyright  Copyright 2016 Clay Freeman. All rights reserved.
   * @license    GNU Lesser General Public License v3 (LGPL-3.0).
   */

  // Load the existing configuration file
  $file     = '/usr/share/shared-hosting/config.json';
  $readfile = is_file($file) ? $file : 
    '/usr/share/shared-hosting/config.example.json';
  $config   = json_decode(file_get_contents($readfile), true);

  // Modify the configuration file with the provided arguments
  $config['email'] = $argv[1]; $config['password'] = $argv[2];

  // Write the updated configuration file
  file_put_contents($file, json_encode($config, JSON_PRETTY_PRINT)."\n");
