#!/bin/sh

# Load the `debconf` library functions
. /usr/share/debconf/confmodule

# Ensure that the user provides a valid e-mail address
mv /etc/letsencrypt/accounts /etc/letsencrypt/accounts."$(date +%s)"
while test -z "$(find /etc/letsencrypt/accounts -name 'private_key.json')"; do
  db_input high shared-hosting/email || true
  db_go
  db_get shared-hosting/email
  certbot register --non-interactive --agree-tos -m "$RET" 2> /dev/null && break
  sleep 1
done

while true; do
  db_input high shared-hosting/mysql-password || true
  db_go
  db_get shared-hosting/mysql-password
  mysql -u root -p"$RET" -e 'QUIT' 2> /dev/null && break
  sleep 1
done
