#!/bin/sh

# Load the `debconf` library functions
. /usr/share/debconf/confmodule

# Ensure that the user provides a valid e-mail address
EMAIL="$(jq -r .email /usr/share/shared-hosting/config.json 2> /dev/null)"
while [ "$1" = "reconfigure" ] || [ -z "$EMAIL" ]; do
  if [ "$1" = "reconfigure" ]; then
    db_subst shared-hosting/email skippable \
      "Press enter to keep the current value."
  fi
  db_input high shared-hosting/email || true
  db_go
  db_get shared-hosting/email
  # Skip the verification process if no changes were made
  if [ "$RET" = "$EMAIL" ]; then break; fi
  # Backup any existing accounts directory
  if [ -e /etc/letsencrypt/accounts ]; then
    mv /etc/letsencrypt/accounts /etc/letsencrypt/accounts."$(date +%s)"
  fi; mkdir -p /etc/letsencrypt/accounts
  certbot register --non-interactive --agree-tos -m "$RET" 2> /dev/null && break
  sleep 1
done

MY_PWD="$(jq -r .password /usr/share/shared-hosting/config.json 2> /dev/null)"
while [ "$1" = "reconfigure" ] || [ -z "$MY_PWD" ]; do
  if [ "$1" = "reconfigure" ]; then
    db_subst shared-hosting/mysql-password skippable \
      "Press enter to keep the current value."
  fi
  db_input high shared-hosting/mysql-password || true
  db_go
  db_get shared-hosting/mysql-password
  mysql -u root -p"$RET" -e 'QUIT' 2> /dev/null && break
  sleep 1
done
