.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Clay Freeman <git@clayfreeman.com>.
.\"
.TH ENABLE-TLS 8 "December 12 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH ENABLE-TLS
enable-tls \- Creates a TLS certificate with the help of Let's Encrypt using the
web root authenticator and enables it.
.SH SYNOPSIS
.B enable-tls
.RI [ options ] " domain"
.SH DESCRIPTION
.B enable-tls
makes use of the convenient, cost-effective, and automated facility of Let's
Encrypt to acquire Domain Validation (DV) certificates for the requested
\fIdomain\fP. DNS must be pointed to the web server prior to running this
command, as it makes use of Let's Encrypt's web root authenticator.
.PP
When enabling TLS for a given \fIdomain\fP, prior server configuration need not
be made as long as the template for the associated site inherits from the
\fLgeneral.conf\fP \fBnginx\fP template. If this is not the case, special
accommodations must be made for the site's template prior to running this
command.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Display the help message.
.TP
.B \-q, \-\-quiet
Do not output any message.
.TP
.B \-V, \-\-version
Display the application version.
.TP
.B \-\-ansi
Force ANSI output.
.TP
.B \-\-no\-ansi
Disable ANSI output.
.TP
.B \-n, \-\-no\-interaction
Do not ask any interactive question.
.TP
.B \-v|vv|vvv, \-\-verbose
Increase the verbosity of messages: 1 for normal output, 2 for more verbose
output and 3 for debug.
.SH SEE ALSO
.BR disable-tls (8).
